export const countryNames = {
  cz: "Czech Republic",
  de: "Germany",
  eg: "Egypt",
  es: "Spain",
  fr: "France",
  gb: "United Kingdom",
  gr: "Greece",
  hk: "Hong Kong",
  hu: "Hungary",
  ie: "Ireland",
  il: "Israel",
  in: "India",
  it: "Italy",
  jp: "Japan",
  lt: "Lithuania",
  lv: "Latvia",
  ma: "Morocco",
  my: "Malaysia",
  ng: "Nigeria",
  nl: "Netherlands",
  no: "Norway",
  pl: "Poland",
  ua: "Ukraine",
  us: "United States",
};
